server:
  port: 8066

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://news-mysql:3306/db_news?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root