server:
  port: 8066

spring:
  #  消息中间件配置
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    # host: localhost
    # host: news-rabbitmq
    host: 8.148.240.171
    port: 5672