server:
  port: 8090

# mabatis配置
mybatis:
  # 别名
  type-aliases-package: com.core.pojo
  # xml配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper的xml文件
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    # 项目名字
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db_news?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
