server:
  port: 8069
  servlet:
    # 虚拟路径
    context-path: /sky
  max-http-header-size: 102400

spring:
  # 多环境配置  激活**环境
  profiles:
    active: dev
  # 连接数据库
  datasource:
    username: root
    password: root
    # serverTimezone时区 中国    useSSL=false不使用安全连接    characterEncoding字符集编码
    url: jdbc:mysql://localhost:3306/jeecg-boot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    # 驱动   mysql8: com.mysql.cj.jdbc.Driver      mysql5: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

jeecg:
  #阿里云oss存储和大鱼短信秘钥配置   未知填??
  oss:
    accessKey: LTAI5tDh7ep2ALGsBexmMo3C
    secretKey: SKotVCXYjsG93vVy1zBSMKiTkCoPDx
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: rafael
  # minio文件上传
  minio:
    minio_url: http://127.0.0.1:9000
    minio_name: ROOTUSER
    minio_pass: CHANGEME123
    bucketName: minio-admin