server:
  port: 8069
  servlet:
    # 虚拟路径
    context-path: /sky
  max-http-header-size: 102400

spring:
  # 多环境配置  激活**环境
  profiles:
    active: dev
  # 连接数据库
  datasource:
    username: root
    password: root123456
    # serverTimezone时区 中国    useSSL=false不使用安全连接    characterEncoding字符集编码
    url: jdbc:mysql://localhost:3306/jeecg-boot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    # 驱动   mysql8: com.mysql.cj.jdbc.Driver      mysql5: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

jeecg:
  #阿里云oss存储和大鱼短信秘钥配置
  oss:
    accessKey: ??
    secretKey: ??
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: rafael
  # minio文件上传
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: otatest